##
## gridmap config
##
cloud_topics: ["/wassp/detections"]
viz_period: 5.0 #s

map:
    res: 1.0
    len_x: 2000.0  # m  :: if no len_y is specified len_y=len_x
    center_x: 0
    center_y: 0
    filename: "/home/kris/temp/gridmap_test.bag"
    frame_id: "utm_local"
    write_period: 10.0 #s
